# CH-9 

# Advance OOP & Numpy

*Polymorphism

*Inheritance

*Abstract class

# Polymorphism

# 1.Method-Overriding

In [2]:
def add(a,b):
    print(a+b)
    
def add(a,b,c):
    print(a+b+c)
    

In [4]:
add(10,20,30)

60


# 2.Operator-Overloading

In [62]:
class point:
    def __init__(self,x,y):
        self.x=x
        self.y=y
    def __str__(self):
        return "x="+str(self.x)+" y="+str(self.y)
    def __add__(self,other):
        x=self.x+other.x
        y=self.y+other.y
        return point(x,y)
    def __sub__(self,other):
        x=self.x-other.x
        y=self.y-other.y
        return point(x,y)
    def __mul__(self,other):
        x=self.x*other.x
        y=self.y*other.y
        return point(x,y)
    def __truediv__(self,other):
        x=self.x/other.x
        y=self.y/other.y
        return point(x,y)
    def __floordiv__(self,other):
        x=self.x//other.x
        y=self.x//other.y
        return point(x,y)
    def __mod__(self,other):
        x=self.x%other.x
        y=self.y%other.y
        return point(x,y)
    def __pow__(self,other):
        x=self.x**other.x
        y=self.y**other.y
        return point(x,y)
    def __lt__(self,other):
        if self.x<other.x:
            if self.y<other.y:
                return True
        return False
    def __gt__(self,other):
        if self.x>other.x:
            if self.y>other.y:
                return True
        return False
    def __le__(self,other):
        if self.x<=other.x:
            if self.y<=other.y:
                return True
        return False
    def __ge__(self,other):
        if self.x>=other.x:
            if self.y>=other.y:
                return True
        return False
    def __ne__(self,other):
        if self.x!=other.x:
            if self.y!=other.y:
                return True
        return False
    def __eq__(self,other):
        if self.x==other.x:
            if self.y==other.y:
                return True
        return False

In [63]:
p1=point(4,31)
p2=point(3,4)

In [64]:
p3=p1+p2
print(p3)
p4=p1-p2
print(p4)
p5=p1*p2
print(p5)
p6=p1/p2
print(p6)
p7=p1//p2
print(p7)
p8=p1%p2
print(p8)
p9=p1**p2
print(p9)
p10=p1<p2
print(p10)
p11=p1>p2
print(p11)
p12=p1<=p2
print(p12)
p13=p1>=p2
print(p13)
p14=p1!=p2
print(p14)
p15=p1==p2
print(p15)


x=7 y=35
x=1 y=27
x=12 y=124
x=1.3333333333333333 y=7.75
x=1 y=1
x=1 y=3
x=64 y=923521
False
True
False
True
True
False


# Inheritance

# 1.Single Inheritance

In [65]:
class parent:
    def fun1(self):
        print("Hello Parent")
class child(parent):
    def fun2(self):
        print("Hello Child")

In [66]:
p=parent()
p.fun1()

Hello Parent


In [68]:
p.fun2()

AttributeError: 'parent' object has no attribute 'fun2'

In [69]:
c=child()
c.fun1()
c.fun2()

Hello Parent
Hello Child


# 2.Multiple Inheritance

In [71]:
class parent1:
    def fun1(self):
        print("Hello Parent1")
class parent2:
    def fun2(self):
        print("Hello Parent2")
class child(parent1,parent2):
    def fun3(self):
        print("Hello Child")

In [75]:
p=parent1()
p.fun1()
p.fun2()
p.fun3()

Hello Parent1


AttributeError: 'parent1' object has no attribute 'fun2'

In [76]:
p1=parent2()
p1.fun1()
p1.fun2()
p1.fun3()

AttributeError: 'parent2' object has no attribute 'fun1'

In [72]:
c=child()
c.fun1()
c.fun2()
c.fun3()

Hello Parent1
Hello Parent2
Hello Child


# 3.Multilevel Inheritance

In [80]:
class gparent:
    def fun1(self):
        print("Hello grand Parent")
class parent(gparent):
    def fun2(self):
        print("Hello Parent")
class child(parent):
    def fun3(self):
        print("Hello Child")

In [81]:
p=gparent()
p.fun1()
p.fun2()
p.fun3()

Hello grand Parent


AttributeError: 'gparent' object has no attribute 'fun2'

In [82]:
p1=parent()
p1.fun1()
p1.fun2()
p1.fun3()

Hello grand Parent
Hello Parent


AttributeError: 'parent' object has no attribute 'fun3'

In [79]:
c=child()
c.fun1()
c.fun2()
c.fun3()

Hello Parent1
Hello Parent2
Hello Child


# 4.Hierarchical Inheritance

In [83]:
class parent(gparent):
    def fun1(self):
        print("Hello Parent")
class child1(parent):
    def fun2(self):
        print("Hello Child")
class child2(parent):
    def fun3(self):
        print("Hello Child")

In [84]:
p1=parent()
p1.fun1()
p1.fun2()
p1.fun3()

Hello Parent


AttributeError: 'parent' object has no attribute 'fun2'

In [85]:
c=child1()
c.fun1()
c.fun2()
c.fun3()

Hello Parent
Hello Child


AttributeError: 'child1' object has no attribute 'fun3'

In [86]:
c=child2()
c.fun1()
c.fun2()
c.fun3()

Hello Parent


AttributeError: 'child2' object has no attribute 'fun2'

# 5.Hybrid Inheritance

In [93]:
class gparent:
    def fun1(self):
        print("Hello grand Parent")
class parent1(gparent):
    def fun2(self):
        print("Hello Parent1")
class parent2:
    def fun3(self):
        print("Hello Parent2")
class child(parent1,parent2):
    def fun4(self):
        print("Hello Child")

In [94]:
gp=gparent()
gp.fun1()
gp.fun2()
gp.fun3()

Hello grand Parent


AttributeError: 'gparent' object has no attribute 'fun2'

In [95]:
p=parent1()
p.fun1()
p.fun2()
p.fun3()

Hello grand Parent
Hello Parent1


AttributeError: 'parent1' object has no attribute 'fun3'

In [96]:
p1=parent2()
# p1.fun1()
# p1.fun2()
p1.fun3()

Hello Parent2


In [97]:
c=child()
c.fun1()
c.fun2()
c.fun3()
c.fun4()

Hello grand Parent
Hello Parent1
Hello Parent2
Hello Child


In [98]:
class g1:
    def fun1(self):
        print(g1)
class g2:
    def fun2(self):
        print(g2)
class p1(g1,g2):
    def fun3(self):
        print(p1)
class p2:
    def fun4(self):
        print(p2)
class p3(g1,g2):
    def fun5(self):
        print(p1)
class c1(p1,p2):
    def fun6(self):
        print(c1)
class c2(p2,p3):
    def fun4(self):
        print(c2)

# MRO(Method Resolution Order)

*Dimond Inheritance

In [113]:
class A:
    def fun(self):
        print("A")
class B(A):
    def fun1(self):
        print("B")
class C(A):
    def fun2(self):
        print("C")
class D(B,C):
    def display(self):
        print("D")

In [115]:
d=D()
d.fun()
d.fun1()
d.fun2()
d.display()

A
B
C
D


In [116]:
print(D.__mro__)

(<class '__main__.D'>, <class '__main__.B'>, <class '__main__.C'>, <class '__main__.A'>, <class 'object'>)


# Super Function[ Super() ]

In [3]:
class parent:
    def display(self):
        print("Hello Parent")
class child(parent):
    def display(self):
        super().display()
        print("Hello Child")

In [4]:
c=child()
c.display()

Hello Parent
Hello Child


* Implement the following hierarchy . The Staff function has name and salary as its data members, the derived class 
Teaching has subject as its data member and the class NonTeaching has department as its data member. The derived 
class method overrides (extends) the methods of the base class.

In [12]:
class staff:
    def __init__(self,name,salary):
        self.name=name
        self.salary=salary
    def display(self):
        print("name=",self.name)
        print("salary=",self.salary)
class teaching(staff):
    def __init__(self,name,salary,subject):
        super().__init__(name,salary)
        self.subject=subject
    def display(self):
        super().display()
        print("subject=",self.subject)
class nonTeaching(staff):
    def __init__(self,name,salary,department):
        super().__init__(name,salary)
        self.department=department
    def display(self):
        super().display()
        print("department=",self.department)

In [13]:
s=staff("Rajesh",50000)
s.display()

name= Rajesh
salary= 50000


In [14]:
t=teaching("Rajesh",50000,"Python")
t.display()

name= Rajesh
salary= 50000
subject= Python


In [15]:
nt=teaching("Rajesh",50000,"coding")
nt.display()

name= Rajesh
salary= 50000
subject= coding


542.Write a program to create a class called Data having “value” as its data member. Overload the (>) and the (<) operator for 
the class. Instantiate the class and compare the objects using _lt_ and _gt_.

class data:
    def __init__(self,value):
        self.value=value
    def __gt__(self,other):
        if self.value>other.value:
            return True
        return False
    def __lt__(self,other):
        if self.value<other.value:
            return True
        return False

In [17]:
a=data(10)
b=data(20)
print(a<b)
print(a>b)

True
False


643. The following illustration creates a class called data. If no argument is passed while instantiating the class a false is 
returned, otherwise a true is returned.

In [33]:
class data:
    def __init__(self,a=None):
        if a:
            self.a=a
            self.status=False
        else:
            self.status=True
    def __str__(self):
        return f"status={self.status}"

In [34]:
a=data(10)
print(a)

status=False


641. Create a class student with following member attributes: roll no, name, age and total marks. Create suitable methods for 
reading and printing member variables. Write a python program to overload ‘==’ operator to print the details of students 
having same marks.

In [46]:
class student:
    def __init__(self,rollno,name,age,totalmarks):
        self.rollno=rollno
        self.name=name
        self.age=age
        self.totalmarks=totalmarks
    def display(self):
        print("name=",self.name)
        print("rollno=",self.rollno)
        print("age=",self.age)
        print("totalmarks=",self.totalmarks)
    def __eq__(self,other):
        if self.totalmarks==other.totalmarks:
            return True
        return False

In [48]:
a=student(1,"Rajesh",19,71)
b=student(2,"Rohan",20,70)
if a==b:
    a.display()
    b.display()
else:
    print(f"{a.name} and {b.name} do not have same marks")

Rajesh and Rohan do not have same marks


# Abstact Class

In [56]:
from abc import ABC,abstractmethod
class Shape(ABC):
    def __init__(self,shape_name):
        self.shape_name=shape_name
    @abstractmethod
    def draw(self):
        pass
class Circle(shape):
    def __init__(self):
        super().__init__("circle")
    def draw(self):
        print("Drawing a Circle")
class Triangle(shape):
    def __init__(self):
        super().__init__("Triangle")
    def draw(self):
        print("Drawing a Triangle")

In [57]:
c=Circle()
c.draw()

Drawing a Circle


In [58]:
t=Triangle()
t.draw()

Drawing a Triangle


657. Write a Python Program to Find the Net Salary of Employee using Inheritance.
 Create three Class Employee, Perks, NetSalary. Make an Employee class as an abstract class.
 Employee class should have methods for following tasks.- To get employee details like employee id, name and salary from user. - To print the Employee details. - return Salary.- An abstract method emp_id.
 Perks class should have methods for following tasks.- To calculate DA, HRA, PF. - To print the individual and total of Perks (DA+HRA-PF).
 Netsalary class should have methods for following tasks.- Calculate the total Salary after Perks.- Print employee detail also prints DA, HRA, PF and net salary.
 Note 1: DA-35%, HRA-17%, PF-12%
 Note 2: It is compulsory to create objects and demonstrating the methods with Correct output.    

In [4]:
from abc import ABC,abstractmethod
class Employee(ABC):
    def __init__(self):
        self.eid=0
        self.name=""
        self.salary=0
    def getdetail(self):
        self.eid=input("Enter employee id=")
        self.name=input("Enter employee name")
        self.salary=int(input("enter employee salary="))
    def display(self):
        print("employee id=",self.eid)
        print("employee name=",self.name)
        print("employee salary=",self.salary)
    def return_salary(self):
        return self.salary
    @abstractmethod
    def emp_id(self):
        pass
class perks(Employee):
    def __init__(self):
        super().__init__()
        self.da=0
        self.hra=0
        self.pf=0
    def emp_id(self):
            return self.eid
    def calculate(self):
        self.da=self.salary*0.35
        self.hra=self.salary*0.17
        self.pf=self.salary*0.12
    def display_perks(self):
        print("DA=",self.da)
        print("HRA=",self.hra)
        print("PF=",self.pf)
        print("total perks=",self.da+self.hra-self.pf)
class Netsalary(perks):
    def __init__(self):
        super().__init__()
        self.net_salary=0
    def calculate_net_salary(self):
        self.net_salary=self.salary+self.da+self.hra-self.pf
    def display_net(self):
        self.display()
        self.display_perks()
        print("total salary=",self.net_salary)

In [5]:
n=Netsalary()
n.getdetail()
n.calculate()
n.calculate_net_salary()
n.display_net()

Enter employee id=1
Enter employee nameRajesh
enter employee salary=50000
employee id= 1
employee name= Rajesh
employee salary= 50000
DA= 17500.0
HRA= 8500.0
PF= 6000.0
total perks= 20000.0
total salary= 70000.0


# Numpy

Most of MCQ[5-7 MARKS]

# Creating Numpy Array

In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
import numpy as np
a=np.array((1,2,3,4,5))
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Dimensions in Array

# 0-D Arrays

In [4]:
import numpy as np
a=np.array(42)
print(a)
print(type(a))

42
<class 'numpy.ndarray'>


# 1-D Arrays

In [5]:
import numpy as np
a=np.array([42,45,49,48,51])
print(a)
print(type(a))

[42 45 49 48 51]
<class 'numpy.ndarray'>


# 2-D Arrays

In [10]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(type(a))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


# 3-D Arrays

In [11]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)
print(type(a))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>


# Chek Number Of Dimensions

In [14]:
import numpy as np
a=np.array(42)
b=np.array([42,45,49,48,51])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Higher Dimensional Arrays

In [18]:
import numpy as np
a=np.array([1,2,3,4,5],ndmin=5)
print(a)
print(a.ndim)

[[[[[1 2 3 4 5]]]]]
5


# Numpy Array Slicing

# 1-D Slicing

In [28]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])

In [29]:
print(a[4:])

[5 6 7]


In [30]:
print(a[0:6:2])

[1 3 5]


In [31]:
print(a[:2])

[1 2]


# 1-D Slicing (Negative slicing)

In [32]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])

In [35]:
print(a[-3:1:-1])

[5 4 3]


In [38]:
print(a[-6:-2])

[2 3 4 5]


# 2-D Slicing

In [ ]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [48]:
print(a[1][1:4])
print(a[1,1:4])

[7 8 9]
[7 8 9]


In [47]:
print(a[:,2])

[3 8]


In [49]:
print(a[:,1:4])

[[2 3 4]
 [7 8 9]]


In [57]:
print(a[::-1,-2:-4:-1])
print(a[:,-2:-4:-1])

[[9 8]
 [4 3]]
[[4 3]
 [9 8]]


In [58]:
print(a[:,2:4])

[[3 4]
 [8 9]]


# 3-D Slicing

In [59]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [60]:
print(a[1,:,2])

[ 9 12]


In [61]:
print(a[:,:,1])

[[ 2  5]
 [ 8 11]]


In [62]:
print(a[:,1,0:2])

[[ 4  5]
 [10 11]]


In [65]:
print(a[:,0,-1:-3:-1])

[[3 2]
 [9 8]]


# Numpy Array Shape

# ~shape answer always tuple

In [67]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print("Shape=",a.shape)

Shape= (2, 4)


In [68]:
a=np.array([[[[[1,2,3,4]]]]])
print("Shape=",a.shape)

Shape= (1, 1, 1, 1, 4)


# Numpy Array Reshaping

# Case 1:Reshape From 1-D To 2-D

In [72]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
a1=a.reshape(2,5)
a2=a.reshape(5,2)
a3=a.reshape(1,10)
a4=a.reshape(10,1)
print(a1)
print(a2)
print(a3)
print(a4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5  6  7  8  9 10]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


# Case 2:Reshape From 1-D To 3-D 

In [76]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a1=a.reshape(1,1,12)
a2=a.reshape(1,12,1)
a3=a.reshape(12,1,1)
a4=a.reshape(2,2,3)
a5=a.reshape(2,3,2)
a6=a.reshape(3,2,2)
a7=a.reshape(1,3,4)
print(a4)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# Unknown Dimension

In [79]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a1=a.reshape(2,-1,3)
print(a1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# Flattening The Arrays

In [81]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a1=a.reshape(-1)
print(a1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# Numpy Array Iterating

# Case 1:Iterating 1-D Array

In [82]:
import numpy as np
a=np.array([1,2,3])
for i in a:
    print(i)

1
2
3


# Case 2:Iterating 2-D Array

In [83]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
for i in a:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10


# Case 3:Iterating 3-D Array

In [84]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in a:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12


# Numpy Joining Array

# Case 1:Concatenating 1-D Array

In [85]:
import numpy as np
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a3=np.concatenate((a1,a2))
print(a3)

[1 2 3 4 5 6]


# Case 2:Concatenating 2-D Array

# Method 1:Axis=0

In [86]:
import numpy as np
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
a3=np.concatenate((a1,a2),axis=0)
print(a3)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Method 2:Axis=1

In [87]:
import numpy as np
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
a3=np.concatenate((a1,a2),axis=1)
print(a3)

[[1 2 5 6]
 [3 4 7 8]]


# Case 3:Concatenating 3-D Array

In [96]:
import numpy as np
a1=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a2=np.array([[[9,10],[11,12]],[[13,14],[15,16]]])
a3=np.concatenate((a1,a2),axis=0)
print(a3)
a4=np.concatenate((a1,a2),axis=1)
print(a4)
a5=np.concatenate((a1,a2),axis=2)
print(a5)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
[[[ 1  2]
  [ 3  4]
  [ 9 10]
  [11 12]]

 [[ 5  6]
  [ 7  8]
  [13 14]
  [15 16]]]
[[[ 1  2  9 10]
  [ 3  4 11 12]]

 [[ 5  6 13 14]
  [ 7  8 15 16]]]


# Numpy Splitting Array

In [7]:
import numpy as np
a=np.array([1,2,3,4,5,6])
a1=np.array_split(a,3)
print(a1)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [8]:
import numpy as np
a=np.array([1,2,3,4,5,6])
a1=np.array_split(a,4)
print(a1)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [9]:
import numpy as np
a=np.array([1,2,3,4,5,6])
a1=np.array_split(a,5)
print(a1)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


# Splitting 2-D Array

In [13]:
import numpy as np
a1=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
a2=np.array_split(a1,3)
print(a2)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [16]:
import numpy as np
a1=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
a2=np.array_split(a1,3)
print(a2)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [15]:
import numpy as np
a1=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
a2=np.array_split(a1,3,axis=1)
print(a2)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int32)]


# Where Function

In [22]:
import numpy as np
a1=np.array([1,2,3,4,5,4,7,4])
x=np.where(a1%2!=0)
print(x)

(array([0, 2, 4, 6], dtype=int64),)


# Numpy Sorting Array

# Sorting 1-D Array

In [23]:
import numpy as np
a1=np.array([3,2,0,1])
print(np.sort(a1))

[0 1 2 3]


In [24]:
import numpy as np
a1=np.array(["b","c","a"])
print(np.sort(a1))

['a' 'b' 'c']


In [25]:
import numpy as np
a1=np.array([True,False,True])
print(np.sort(a1))

[False  True  True]


# Sorting 2-D Array

In [26]:
import numpy as np
a1=np.array([[3,2,4],[5,0,1]])
print(np.sort(a1))

[[2 3 4]
 [0 1 5]]


# Sorting 3-D Array

In [27]:
import numpy as np
a1=np.array([[[3,2,4],[5,0,1]],[[3,2,4],[5,0,1]]])
print(np.sort(a1))

[[[2 3 4]
  [0 1 5]]

 [[2 3 4]
  [0 1 5]]]


# Descending Order

In [28]:
import numpy as np
a1=np.array([3,2,0,1])
print(np.sort(a1)[::-1])

[3 2 1 0]


In [29]:
import numpy as np
a1=np.array([[3,2,4],[5,0,1]])
print(np.sort(a1)[:,::-1])

[[4 3 2]
 [5 1 0]]


In [30]:
import numpy as np
a1=np.array([[[3,2,4],[5,0,1]],[[3,2,4],[5,0,1]]])
print(np.sort(a1)[:,:,::-1])

[[[4 3 2]
  [5 1 0]]

 [[4 3 2]
  [5 1 0]]]


# Random Module

In [49]:
#-->give randomly answer
from numpy import random
x=random.randint(100)
print(x)

64


In [56]:
#-->give 0 to 1 value
from numpy import random
x=random.rand()
print(x)

0.33395433168329947


In [54]:
#-->give randomly 5 value
from numpy import random
x=random.randint(100,size=(5))
print(x)

[96 99 37 10  2]


In [55]:
#-->give randomly 3x4 matrix
from numpy import random
x=random.randint(100,size=(3,4))
print(x)

[[53 60 25 62]
 [80 62 74 70]
 [28 69 12 67]]


In [58]:
#-->give 0 to 1randomly 5 value
from numpy import random
x=random.rand(5)
print(x)

[0.91605667 0.82803845 0.39762807 0.38703714 0.68897668]


In [60]:
#-->give 0 to 1randomly 3x5 value
from numpy import random
x=random.rand(3,5)
print(x)

[[0.43411606 0.3360735  0.72370532 0.37736153 0.18674706]
 [0.38738162 0.32015592 0.76189137 0.48502611 0.96489613]
 [0.09468316 0.38184454 0.4798623  0.68924751 0.37716798]]


In [66]:
z=random.choice([3,5,7,9])
print(z)

5


In [67]:
z=random.choice([3,5,7,9],size=(3,5))
print(z)

[[5 3 3 3 7]
 [7 9 9 9 5]
 [9 5 3 3 5]]
